# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://sunbufu.github.io
date_format: "ordinal"
title: 孙不服的博客
subtitle: "Life is great and everything will be OK."
description: "孙不服的博客"
keywords: 孙不服的博客, sunbufu
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: sunbufu
organization: 字节跳动
organization_url: https://www.bytedance.com
github_username: sunbufu
location: Beijing, China
email: sunyoubufu@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
#     - jekyll-html-pipeline
#     - jekyll-mentions
collections:
  wiki:
    output: true
    permalink: /wiki/:path/

repository: sunbufu/sunbufu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#  username:
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: sunbufu
#    repo: 生活-comments
#    oauth:
#        client_id: 7367b7b7d38a1851c8c4
#        client_secret: c8f83aea051671a33b02a9581678b75aa59cf2b6
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: sunbufu
  repo: blog-comments
  clientID: 59e22883393cb32a3b96
  clientSecret: cc301d2d467412579aa96d8d1c856ee0ee623478
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
  # 是否支持全文搜索
  fulltext: false
  # 最多显示多少条搜索结果
  limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
baidu:
  analytics_id: f3c45aa73d5475ac1af92f29b0912e09